version: '3.8'

services:

  postgres-primary:
    image: postgres:14-alpine
    container_name: my_postgres_primary 
    restart: always
    # Sử dụng networks để các container giao tiếp ổn định qua tên service
    networks:
      - postgres-net
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    # Chúng ta sẽ không dùng POSTGRES_HOST_AUTH_METHOD nữa vì script đã xử lý
    command: 
      - "postgres"
      - "-c"
      - "wal_level=replica"
      - "-c"
      - "hot_standby=on"
      - "-c"
      - "max_wal_senders=10"
      - "-c"
      - "max_replication_slots=10"
      # Thêm listen_addresses = '*' để chắc chắn nó lắng nghe trên tất cả các interface mạng
      - "-c"
      - "listen_addresses=*"
    volumes:
      - postgres_primary_data:/var/lib/postgresql/data
      # Mount script vào thư mục khởi tạo của postgres
      # Mọi file .sh trong thư mục này sẽ được chạy khi container khởi tạo lần đầu
      - ./init-primary.sh:/docker-entrypoint-initdb.d/init-primary.sh
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5


  postgres-replica-1:
    image: postgres:14-alpine
    container_name: my_postgres_replica_1
    restart: always
    networks:
      - postgres-net
    ports:
      - "5433:5432"
    environment:
      PGUSER: ${DATABASE_USER}
      PGPASSWORD: ${DATABASE_PASSWORD} 
    depends_on:
      postgres-primary:
        condition: service_healthy
    volumes:
      - postgres_replica_1_data:/var/lib/postgresql/data
      # Mount script entrypoint tùy chỉnh vào container
      - ./entrypoint-replica.sh:/usr/local/bin/entrypoint-replica.sh
    # Chạy script tùy chỉnh của chúng ta
    command: entrypoint-replica.sh postgres

  postgres-replica-2:
    image: postgres:14-alpine
    container_name: my_postgres_replica_2
    restart: always
    networks:
      - postgres-net
    ports:
      - "5434:5432"
    environment:
      PGUSER: ${DATABASE_USER}
      PGPASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      postgres-primary:
        condition: service_healthy
    volumes:
      - postgres_replica_2_data:/var/lib/postgresql/data
      # Mount script entrypoint tùy chỉnh vào container
      - ./entrypoint-replica.sh:/usr/local/bin/entrypoint-replica.sh
    # Chạy script tùy chỉnh của chúng ta
    command: entrypoint-replica.sh postgres

  redis_cache:
    image: redis:7-alpine
    container_name: my_redis_cache
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD} 
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_primary_data: {}
  postgres_replica_1_data: {}
  postgres_replica_2_data: {}
  redis_data: {}

networks:
  postgres-net:
    driver: bridge